services:
    marttiphpbb.jqueryuidatepicker.listener:
        class: marttiphpbb\jqueryuidatepicker\event\listener
        arguments:
            - '%core.root_path%'
            - '@config'
        tags:
            - { name: event.listener }